import './globals.css'
import { Nunito_Sans } from 'next/font/google'
import Provider from '@redux/provider'
import Navbar from '@components/Base/navbar'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const nunito = Nunito_Sans({
  subsets: ['latin'],
  variable: '--font-roboto'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} font-sans`}>
        <Provider>
          <Navbar />
          <ToastContainer />
          {children}
        </Provider>
      </body>
    </html>
  )
}
