import './globals.css'
import { Lato, Inter } from 'next/font/google'
import localFont from 'next/font/local'
import Provider from '@redux/provider'
import Navbar from '@components/Base/navbar'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import UpComingEvent from '@components/Base/upComingEvent'
import ContactPopUpBtn from '@components/Base/contactPopUpBtn'
import ShowEvent from '@components/Base/showEvent'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-roboto'
})
const myFont = localFont({
  src: './fanwood-webfont.woff',
  display: 'swap',
  variable: '--font-myFont'
})
const heading = localFont({
  src: './GoudyStM-webfont.woff',
  display: 'swap',
  variable: '--font-heading'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-bg'>
      <body className={`${inter.variable} ${myFont.variable} ${heading.variable} custom-scrollbar font-sans w-screen overflow-x-hidden`}>
        <Provider>
          <ShowEvent />
          <ContactPopUpBtn />
          <UpComingEvent />
          <Navbar />
          <ToastContainer />
          {children}
        </Provider>
      </body>
    </html>
  )
}
