import './globals.css'
import { Nunito_Sans, Fira_Mono } from 'next/font/google'
import localFont from 'next/font/local'
import Provider from '@redux/provider'
import Navbar from '@components/Base/navbar'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const nunito = Nunito_Sans({
  subsets: ['latin'],
  variable: '--font-roboto'
})
const fira = Fira_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-fira'
})

const myFont = localFont({
  src: './fanwood-webfont.woff',
  display: 'swap',
  variable: '--font-myFont'
})
const heading = localFont({
  src: './GoudyStM-webfont.woff',
  display: 'swap',
  variable: '--font-heading'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-body'>
      <body className={`${nunito.variable} ${myFont.variable} ${heading.variable} font-sans max-w-screen overflow-x-hidden`}>
        <Provider>
          <Navbar />
          <ToastContainer />
          {children}
        </Provider>
      </body>
    </html>
  )
}
